# Generated by Django 2.2.7 on 2019-11-20 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='code',
            name='task_code',
            field=models.TextField(default=''),
        ),
    ]
