# Generated by Django 2.2.7 on 2019-11-27 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='code',
            name='score',
            field=models.IntegerField(default=0),
        ),
    ]
