# Generated by Django 2.2.7 on 2019-12-02 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0002_news'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='News',
            new_name='New',
        ),
    ]
