# Generated by Django 2.2.7 on 2019-12-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0004_auto_20191202_0944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='img',
            field=models.ImageField(default='news_img/news.png', upload_to='news_img'),
        ),
    ]
