# Generated by Django 2.2.7 on 2019-12-02 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0005_auto_20191202_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='img',
            field=models.ImageField(default='news_img/news.png', upload_to=''),
        ),
    ]
