# Generated by Django 2.2.7 on 2019-12-02 10:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myFirstApp', '0007_auto_20191202_0948'),
    ]

    operations = [
        migrations.RenameField(
            model_name='new',
            old_name='img',
            new_name='news_img',
        ),
    ]
